### ISSUE TITLE
Ensure codevcov is well configured on our projects

### ISSUE THREAD

**Issue by ssbarnea** [ansible/team-devtools#169]
- [ ] codecov token is present in testing git environment (usually named 'test') and we activate it for jobs via `environment: test`.
- [ ] we use v4 of the uploader with the settings as below:

```yaml
        uses: codecov/codecov-action@v4
        with:
          name: ${{ matrix.passed_name }}
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
          fail_ci_if_error: true
```
- [ ] codecov action result is a required action alongside 'check' one, so we do not merge changes that are not blessed by codecov itself. If app does not report status, you might need to go to https://github.com/apps/codecov/installations/398480 and ensure that repository is activated.

- [ ] ensure `codecov.yml` has the content below:

```yaml
# codecov.yml
comment: false
coverage:
  status:
    patch: true # we want github annotations
```

If you see `require_ci_to_pass: true` in file above, remove it as its true behavior does prevent codecov from reporting the status check even when it should.

## Progress

SMEs: Please check your project once you have confirmation that codecov action was updated v4 and that codecov is reporting the status correct on new PRs and that codecov/project is a `required` check (branch protection).

- [x] ansible/ansible-compat
- [x] ansible/ansible-lint
- [x] ansible/ansible-navigator
- [x] ansible/ansible-creator
- [x] ansible/molecule
- [x] ansible/tox-ansible
- [x] ansible/pytest-ansible
- [x] ansible/ansible-development-environment
- [x] ansible/ansible-dev-tools
- [x] ansible/creator-ee
