### ISSUE TITLE
Using WSL1 github workflows

### ISSUE THREAD

**Issue by ssbarnea** [ansible/team-devtools#29]
- All default GHA runners can only use `WSL1`, so we cannot make use of `docker` or `podman` on them.
- We might be able to spawn our own runners that would be able to make use of WSL2

# Tricks about easily integrating WSL1 actions

Here is a model that should allow us to use WSL, as it includes few tricks we need to consider.

Do not try to use expressions inside `shell:` for specific steps as that is not allowed. Still the trick with defaults works fine.

One important observation is that `env:` does not reach WSL job by default, so we need to pass environment variables manually. Read https://github.com/Vampire/setup-wsl/discussions/9

```yaml

jobs:
    runs-on: ${{ matrix.os }}
    env:
      FORCE_COLOR: 1
      # colon separated list of env vars to be passed to wsl-bash:
      WSLENV: FORCE_COLOR:TOX_ENV
    defaults:
      run:
        shell: ${{ matrix.shell || 'bash'}}
    matrix:
      ...
      include:
        - os: windows-latest
          shell: "wsl-bash {0}"

    steps:
      - name: Activate WSL1
        if: "contains(matrix.shell, 'wsl')"
        uses: Vampire/setup-wsl@v1

      - run: echo 123
        env:
          TOX_ENV: foo  # do not forget to include it in WSLENV

      - # run a command directly under Windows (not wsl)
        run: dir
        if: "runner.os == 'Windows'"
        shell: bash  # or other but cannot omit it, else will be under wsl
```
